[tool.poetry]
name = "hexlet_pytest"
version = "0.1.0"
description = ""
authors = ["Alexey-Shepelev <alexey.sailor@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
